# Ici ça compose
# PAS TOUCHER
# C'est pour le déploiement de l'application
# 02/02/2024 - Pour PVE

services:
  web:
    image: linksawordkening:latest
    entrypoint: bash /var/www/html/init.sh
    ports:
      - "xxxx:80"
      - "8765:8765"
    volumes:
      - lechemin:/var/www/html
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M